let data = {
  veggies: {
    good: [
      'asparagus',
      'avocado',
      'beans(black eyed peas, garbanzo, lentils, pinto, white, most dried beans)',
      'beets',
      'broccoli',
      'brussels sprouts',
      'cabbage',
      'carrots',
      'cauliflower',
      'celery',
      'chives',
      'corn',
      'cucumber',
      'eggplant',
      'green beans',
      'greens(collard greens, kale, mustard greens, okra, swiss chard, spinach, bok choy)',
      'lettuce & most salad greens',
      'mushrooms',
      'olives(black)',
      'parsley',
      'peas(green, snow peas, split peas)',
      'bell peppers(yellow, orange, red)',
      'potatoes(white, yams)',
      'pumpkin',
      'radishes',
      'rhubarb',
      'rutabaga',
      'squash(summer, winter, zucchini)',
      'turnips',
    ],
    maybe: [
      'beans(fava, kidney beans, lima beans, black beans)',
      'bell peppers(green)',
      'olives(green)',
      'greens(chicory, dandelion greens, purslane,)',
      'turnip greens',
      'leeks(cooked)',
      'onions(white, red, cooked bulb onion, raw green)',
      'tomatoes(homegrown, low acid)',
      'watercress',
    ],
    bad: [
      'chili peppers',
      'onions(raw bulb onions)',
      'pickles',
      'sauerkraut',
      'soy beans(edamame, roasted)',
      'tomato(tomato sauces, tomato juice)',
      'tofu',
    ],
  },
  fruit: {
    good: [
      'apples(Gala, Fuji, Pink Lady)',
      'applesauce(homemade with Gala, Fuji or Pink Lady apples)',
      'blueberries',
      'coconut(without preservatives)',
      'dates(without preservatives)',
      'pears',
      'watermelon',
    ],
    maybe: [
      'applesauce(commercial or baby)',
      'apricots',
      'bananas',
      'berries(blackberries, raspberries, olallieberries)',
      'cherimoya',
      'cherries(fresh, maraschino)',
      'citrus peels',
      'currants',
      'figs',
      'mango',
      'melon(Crenshaw, honeydew)',
      'peaches',
      'plums',
      'raisins(brown)',
      'rhubarb',
    ],
    bad: [
      'berries(cranberries, most)',
      'citrus(lemons, limes, oranges, grapefruit)',
      'dried fruit(with preservatives)',
      'grapes',
      'guava',
      'kiwi fruit',
      'melons(cantaloupe)',
      'nectarines',
      'passion fruit',
      'papaya',
      'persimmon',
      'pineapple',
      'starfruit',
      'strawberries',
      'raisins(golden)',
    ],
  },
  protein: {
    good: [
      'eggs',
      'poultry(chicken, turkey)',
      'fish',
      'beef',
      'seafood(clams, crabmeat (not canned), lobster, shrimp)',
      'lamb',
      'pork',
      'protein powder(whey, egg whites)',
      'veal',
      'liver(beef or chicken)',
    ],
    maybe: [
      'garden/veggie burgers(without soy products)',
      'beef(corned beef)',
      'sandwich meats(liverwurst, ham (fresh or boiled, without heavy preservatives or flavorings.))',
      'bacon',
      'anchovies',
      'caviar',
      'prosciutto',
      'sausages(without problem ingredients)',
    ],
    bad: [
      'cured meats(bologna, pepperoni, salami)',
      'canned crab meat',
      'hot dogs',
      'sausage(most)',
      'smoked fish',
      'soy products(soy veggie patties, protein, powder, tofu)',
    ],
  },
  grains: {
    good: [
      'breads(corn bread, oat bread, pita, potato bread, white bread, Italian sweet bread, whole wheat bread (i.e. Ezekiel))',
      'cereals(most cereals without problem)',
      'ingredients, oat cereal, rice cereal(hot or cold)',
      'crackers(matzo)',
      'grains(couscous, grits, millet, quinoa, spelt)',
      'flours(buckwheat, wheat)',
      'pasta',
      'rice',
    ],
    maybe: [
      'breads(rye, sourdough)',
      'cereals(instant packaged hot cereal)',
      'crackers(without problem ingredients)',
      'grain(amaranth)',
    ],
    bad: [
      'breads(made with unsafe ingredients and/or heavily processed and fortified)',
      'cereals(heavily preserved, sweetened, heavily fortified, flavored)',
      'flour(soy)',
      'pasta(prepared or boxed pasta dishes)',
      'rice(boxed dishes)',
    ],
  },
  dairy: {
    good: [
      'cheeses(American, mozzarella, cheddar cheese (mild), feta, ricotta, string cheeses)',
      'cream cheese',
      'cottage cheese',
      'ice cream(most)',
      'milk',
      'milk substitutes(Lactaid)',
      'sherbet(no citrus or chocolate flavors)',
      'Rice Dream® dessert(vanilla)',
      'whipped cream(Cool Whip)',
    ],
    maybe: [
      'cheeses(blue cheese, brie, brick parmesan, camembert, cheddar cheese (sharp), edam, emmenthaler, gruyere hard jack, Monterey Jack, parmesan (fresh & canned), Roquefort, stilton, Swiss)',
      'buttermilk',
      'sour cream(accent on a baked potato or soup)',
      'pizza(plain, chicken & garlic, veggie or made with)',
      'white sauce(no pepperoni)',
      'sorbet',
      'yogurt(blueberry, vanilla, plain)',
    ],
    bad: [
      'cheeses(processed, Cheez Whiz)',
      'ice cream(caution with citrus or chocolate)',
      'flavors',
      'soy products(soy milk, soy cheeses)',
    ],
  },
  nuts: {
    good: [
      'almonds',
      'cashews',
      'peanuts',
    ],
    maybe: [
      'macadamia',
      'pecans',
      'walnuts',
      'sunflower seeds',
    ],
    bad: [
      'philberts',
      'hazelnuts',
      'pecans',
      'pistachios',
    ],
  },
  sweeteners: {
    good: [
      'brown sugar',
      'honey',
      'sugar',
    ],
    maybe: [
      'splenda(sucralose)'
    ],
    bad: [
      'acesulfame K',
      'aspartame',
      'Nutrasweet',
      'saccharine',
      'SweetN-Low',
      'stevia',
    ],
  },
  fats: {
    good: [
      'butters(almond, peanut)',
      'oils(canola, coconut, corn, olive, peanut, safflower, sesame, soy)',
      'margarine',
      'lard',
      'shortening',
      'salad dressing(homemade without problem ingredients)',
    ],
    maybe: [
      'mayonnaise',
      'tahini',
      'shortening(butter-flavored)',
    ],
    bad: [
      'oils(check label)',
      'salad dressings(most)',
    ],
  },
  seasonings: {
    good: [
      'allspice',
      'almond extract',
      'anise',
      'basil',
      'caraway seed',
      'coriander',
      'dill',
      'fennel',
      'garlic',
      'mace',
      'marjoram',
      'oregano',
      'poppy seed',
      'rosemary',
      'sage',
      'salt in small quantities',
      'thyme',
      'tarragon',
      'vanilla extract',
    ],
    maybe: [
      'black pepper',
      'celery seed',
      'cilantro',
      'cinnamon(powdered)',
      'citric acid(in small quantities)',
      'cumin(small amt)',
      'dried parsley',
      'dried chervil',
      'ginger',
      'lemon extract',
      'mayonnaise',
      'malt powder',
      'nutmeg',
      'onion powder',
      'orange extract',
      'turmeric',
    ],
    bad: [
      'ascorbic acid',
      'autolyzed yeast',
      'BHA and BHT',
      'benzoates',
      'catsup(ketchup)',
      'cayenne',
      'cloves',
      'chili powder',
      'horseradish',
      'hot curry powder',
      'hydrolyzed protein',
      'meat tenderizers',
      'miso',
      'mustard',
      'oleoresin paprika',
      'paprika',
      'pickles',
      'red pepper',
      'soy sauce',
      'tamari',
      'vinegar',
      'worcestershire sauce',
      'MSG(monosodium glutamate)',
      'metabisulfites',
      'sulfites',
    ],
  },
  beverages: {
    good: [
      'water',
      'juice(blueberry, pear)',
      'milk',
      'milk substitutes',
      'milkshake',
      'tea(chamomile, peppermint)',
      'non-dairy creamers',
      'eggnog',
    ],
    maybe: [
      'juice(low-acid orange, grape, some apple, baby)',
      'coffee(herbal, low-acid decaf, roasted carob)',
      'tea(alfalfa, roasted carob)',
      'soda(root beer with ice (decaffeinated, not diet))',
      'sports drinks(test to find one that works for you (e.g., blue Gatorade))',
    ],
    bad: [
      'alcohol(not only irritating to the bladder but also contraindicated with many IC medications)',
      'water(arbonated, vitamin, flavored)',
      'juice(cranberry, orange, acai)',
      'milk(chocolate, soy)',
      'coffee(regular, decaf)',
      'teas(regular, green, herbal, iced)',
      'sodas(colas, citrus, orange, diet)',
      'drink powders(such as Kool-aid, lemonade, orange, or powdered ice tea drinks)',
      'sports drinks',
      'energy drinks(guarana, mate)',
    ],
  },
  miscellaneous: {
    good: [

    ],
    maybe: [

    ],
    bad: [

    ],
  },
}

module.exports = {
  data: data
}

